name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.8"

      - name: Run Terraform plan
        run: terraform plan -out=terraform_plan.out

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: terraform_plan.out
